### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by Fayeben** [AllenXiangX/SnowflakeNet#10]
May I ask the software used for visualization, thanks!

**Comment by AllenXiangX** [comment]
Hi, we use [keyshot](https://www.keyshot.com/) for visualization.

**Comment by Fayeben** [comment]
Hi, what format should the point cloud be converted into when using KeyShot visualization? thank you~

**Comment by AllenXiangX** [comment]
The format is .obj, more details are in the [visualization folder](https://github.com/AllenXiangX/SnowflakeNet/tree/main/visualization#visualization-code-for-point-splittings).

**Comment by Fayeben** [comment]
Thank you for your patient reply!
