### ISSUE TITLE
How to read Shapenet lmdb file?

### ISSUE THREAD

**Issue by EternityDS** [AllenXiangX/SnowflakeNet#11]
Hi,

Thanks for your work!

I noticed that your public shapenet training data is saved in 'train.lmdb'. May I ask how you read shapenet data from lmdb file？

**Comment by AllenXiangX** [comment]
Hi, you can refer to [GRNet](https://github.com/hzxie/GRNet/blob/master/utils/lmdb_serializer.py) to read lmdb file.
