### ISSUE TITLE
Training with special point cloud dataset 

### ISSUE THREAD

**Issue by ema2161** [AllenXiangX/SnowflakeNet#14]
Hi,
I want to use myself training dataset, dose it possible?
Could I set each of these point cloud dataset to a fixed size of 200000 points for-example, instead of 16348 points which you had set for pcn dataset?
The best
Ema

**Comment by AllenXiangX** [comment]
Hi, 
You can change the parameters (Nc, N0 and up_factors [#](https://github.com/AllenXiangX/SnowflakeNet/blob/93e7151610765e7e2b41ace2d03c8750f0b6c80c/models/model.py#L158), [#](https://github.com/AllenXiangX/SnowflakeNet/blob/93e7151610765e7e2b41ace2d03c8750f0b6c80c/core/train_pcn.py#L55)) of the network according to your need.

**Comment by ema2161** [comment]
Thanks, would you  please tell me some comments about setting of other parameters that I have  to change or prepare for a new dataset? for example about .json file, how can I set it to myself data?
 Best Regards
Ema

**Comment by ema2161** [comment]
Hi, I have two groups of ASCII files. each of them contains 2048 rows and 3 columns of coordinates as gt and partial files. I want to feed them to the snowflakenet by combining them with the training completion3D dateset. How can I change them into the .h5 files?  Do I have to use special software? Appreciate!

**Comment by ema2161** [comment]
Dear Allen Xiang
Thanks to your reply,  I have about 200  ascii files of gt and their
corresponding  partial point cloud dataset  that are too few to train  a
deep learning model! So,  I'm not sure how I can feed them into Snowflakenet.
I would be very grateful if you could guide me how I can train or improve
that model with my ascii files? Does it need to change the format of files
to integrate with other existing input data? if yes what format they have
to be and what dataset do you suggest?  or if I just need to tune the pre
obtained model weights with my data how can I do it?
The kind Regards
Ema
