### ISSUE TITLE
Code for visualization

### ISSUE THREAD

**Issue by qinglew** [AllenXiangX/SnowflakeNet#4]
Thank you very much for releasing the code. I'm seeking a good visualization tool for point cloud. According to your paper, the visualized point cloud is beautiful. Could you please release the code for visualization?

**Comment by AllenXiangX** [comment]
Hi, the visualization code will be released in a few days.

Best,
Allen

**Comment by AllenXiangX** [comment]
> Thank you very much for releasing the code. I'm seeking a good visualization tool for point cloud. According to your paper, the visualized point cloud is beautiful. Could you please release the code for visualization?

**Comment by AllenXiangX** [comment]
> Thank you very much for releasing the code. I'm seeking a good visualization tool for point cloud. According to your paper, the visualized point cloud is beautiful. Could you please release the code for visualization?

**Comment by AllenXiangX** [comment]
Hi, the visualization code for point splitting has been released, enjoy it!

**Comment by AllenXiangX** [comment]
> Thank you very much for releasing the code. I'm seeking a good visualization tool for point cloud. According to your paper, the visualized point cloud is beautiful. Could you please release the code for visualization?

Hi, the visualization code for point splitting has been released, enjoy it!
