### ISSUE TITLE
Need  explanation about Output files

### ISSUE THREAD

**Issue by ema2161** [AllenXiangX/SnowflakeNet#5]
Thanks about the code, I need some information about the output files. For example for the chair class  of pcn there are 5 folders as pcd0 to pcd3 and pcdc with many files in each of them. First what are they and why are they in 5 different files and second, what kind of tools do you suggest for visualizing and considering them?
I found that all of the  output .h5 files  have the same data values!

**Comment by AllenXiangX** [comment]
Hi, pcdc, pcd0, pcd1, pcd2, pcd3 are Pc, P0, P1, P2, P3 in the paper.  You can change the core/inference_*.py file according to your need.
We use open3 for visualizing point cloud.

> I found that all of the output .h5 files have the same data values!

Do you mean that .h5 files all have the same key 'data'? you can access the point cloud by
```
f = h5py.File('path_to_pcd.h5', 'r');
pcd = f['data'][:]
```

**Comment by MaryElna** [comment]
Hi, I tried to access the point clouds with the code you mentioned, but some files have no key! Or maybe libraries are needed to import or install. I ll be appreciate to let me know the solution.
![image](https://user-images.githubusercontent.com/60619370/132671852-73ff5c33-4395-4eeb-8fc4-f8e853acaa05.png)

**Comment by AllenXiangX** [comment]
> Hi, I tried to access the point clouds with the code you mentioned, but some files have no key! Or maybe libraries are needed to import or install. I ll be appreciate to let me know the solution.
> ![image](https://user-images.githubusercontent.com/60619370/132672655-4f88ebf2-40e1-47ff-9d17-adf5d277b38e.png)

I'm sorry I never met problem like this, did you change the inference file? are all .h5 files have no key or just some of them?  my suggestion is to debug the inference file and check if the saving function (utils.io.IO.put) is working.

**Comment by Zhou-Yuen** [comment]
> Hi, I tried to access the point clouds with the code you mentioned, but some files have no key! Or maybe libraries are needed to import or install. I ll be appreciate to let me know the solution.
> ![image](https://user-images.githubusercontent.com/60619370/132672655-4f88ebf2-40e1-47ff-9d17-adf5d277b38e.png)

hi,could you share me the dataset with me?my conmputer can"t download.Thank you very much!!!
