### ISSUE TITLE
How to generate point clouds with the resolutions of 4096 and 8192?

### ISSUE THREAD

**Issue by ToddBear** [AllenXiangX/SnowflakeNet#6]
Thanks for your job

**Comment by AllenXiangX** [comment]
Hi, you need to change up_factors of the model to generate point clouds with different resolutions. for example
change
```
model = Model(dim_feat=512, up_factors=[4, 8])
```
to
```
model = Model(dim_feat=512, up_factors=[4, 2, 2, 2])
```
will work for you. But that means more intermediate outputs, you need to train the network from scratch.

**Comment by ToddBear** [comment]
Oh, i see, thanks for your reply.
