### ISSUE TITLE
L1 chamfer distance for PCN dataset is  5.07*10^(-3), which is better than 7.21*10^(-3) in the paper, is this correct?

### ISSUE THREAD

**Issue by zichang06** [AllenXiangX/SnowflakeNet#9]
Hi, I trained the model based on the PCN dataset. The average L1 chamfer distance is 5.15*10^(-3). The pre-trained model you provided is 5.07*10^(-3), which is better than the data 7.21*10^(-3) in the paper. Except for the dataset path, I did not modify your code. Is this result correct?

**Comment by AllenXiangX** [comment]
Hi, I think it's probably because the data you used for testing is not right. 5.0710^(-3) is too low.

**Comment by zichang06** [comment]
> Hi, I think it's probably because the data you used for testing is not right. 5.0710^(-3) is too low.

Thank you~ The dataset accesseed in my code was indeed wrong. I have already fixed this problem and get the same result in your paper.
(๑•̀ㅂ•́)و✧
